name: Generate and Update Blocklist

on:
  schedule:
    - cron: '0 8 * * *' # Run daily at 08:00 UTC
  workflow_dispatch:

jobs:
  generate_and_update:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python and pip
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install requirements for et2dns
        run: pip install -r requirements.txt
      
      - name: Download ET Open Suricata 5 rules
        run: bash fetch_et_open.sh
      
      - name: Generate hosts files from ET Open rules
        run: |
          python3 et2dns.py --rules emerging-all.suricata5.rules
      
      - name: Commit and push changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add output/*
          git commit -m "Update generated files"
          git push
